project:
  name: MyApp
  version: 1.0.0
  description: My Application Description
  company: ''
  icon: app_icon.ico
  main_file: main.py
build:
  output:
    directory: dist
    filename: my_app.exe
  options:
    standalone: true
    onefile: true
    splash_screen: ''
    remove_output: true
  include:
    packages: []
    plugins: []
    data_dirs:
    - source: resources
      target: resources
    external_data:
    - '*.dll'
    files:
    - requirements.txt
    - readme.md
    - '*.json'
  copy_beside:
  - resources
installer:
  enabled: true
  output:
    directory: dist
    filename: my_app_installer.msi
  metadata:
    manufacturer: Your Company
    product_name: My Application
    upgrade_code: ''
  ui:
    banner_image: banner.bmp
    dialog_image: dialog.bmp
  license_file: license.rtf
  shortcuts:
    desktop: true
    start_menu: true
debug:
  enabled: false
  console:
    mode: disabled
    stdout: null
    stderr: null
exclude:
- __pycache__
- '*.pyc'
- '*.pyo'
- '*.pyd'
- build
- dist
